# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
- job: Linux
  pool:
      vmImage: 'Ubuntu-16.04'

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo $BUILD_BUILDNUMBER
      echo $SOURCE_BRANCH_NUMBER
      env
    displayName: 'Run a multi-line script'
  
- job: Windows
  pool:
      vmImage: 'vs2017-win2016'
  variables:
      EPICS_HOST_ARCH: 'windows-x64-static'
  
  steps:
  - script: |
      rem %BUILD_BUILDNUMBER%
      rem %SOURCE_BRANCH_NUMBER%
  - powershell: |
      $path = "test"
      $destination = "areaDetector-$env:EPICS_HOST_ARCH.zip"
      $exclude = @("*.git*")
      $files = Get-ChildItem -Path $path -Exclude $exclude
      Compress-Archive -Path $files $destination -CompressionLevel Fastest
      dir 
    displayName: Create archive

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: stuwilkins
      repositoryName: stuwilkins/azure-pipeline-test
      action: 'edit'
      target: '$(Build.SourceVersion)'
      assets: '*.zip'
      assetUploadMode: 'delete'
      tagSource: 'Git tag'
      tag: 'v0.1'
    displayName: 'Create GitHub Release'
