# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
- job: Linux
  pool:
      vmImage: 'Ubuntu-16.04'
  variables:
      EPICS_HOST_ARCH: 'linux_x86-64'

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo $BUILD_BUILDNUMBER
      echo $SOURCE_BRANCH_NUMBER
      tar cvzf areaDetector-$EPICS_HOST_ARCH.tar.gz test
    displayName: 'Run a multi-line script'
  
- job: Windows
  pool:
      vmImage: 'vs2017-win2016'
  variables:
      EPICS_HOST_ARCH: 'windows-x64-static'
  
  steps:
  - script: |
      curl -Lo boost.zip  https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.zip
    displayName: Build Boost

